import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

// Correct font setup with valid weights
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "600", "700"], // Ensures valid weights
});

const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  variable: "--font-plex",
  weight: ["300", "400", "500", "600"], // Ensures valid weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${plexSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
